### PR TITLE
Fix run() to use subprocess.run for shell escaping

### PR DESCRIPTION
**Pull request by linalim**
Fix command type in run() from string command to an array of commands (by importing subprocess.run instead of subprocess.getoutput) in order to avoid unnecessary escaping in regex patterns

### CODE REVIEW

**Comment by securisec** [comment]
@linalim can you please provide some examples of both cases on how the regex will be passed? Also, not a fan of `from subprocess import run` as it creates a possible namespace issue because the class has a `run` method already.

**Comment by linalim** [comment]
Here are two examples of failing cases:

- `r'''["]'''`
- `r'''\'''`

I also updated the PR to avoid namespace conflicts.

**Comment by securisec** [comment]
Thank you for resolving the issues @linalim . Thank you also for updating some of the methods to handle array of strings. Can you make the same update to all the other methods too? Some the stood out in my brief check was `threads` and `engine`, but there are others. Also, can you make sure that regexes like `\w` or `\b` isnt breaking?

**Comment by linalim** [comment]
All other methods should be updated now. I've also checked that escaped characters are not breaking.

**Pull request merged**
